version: '3.1'

volumes:
  covidb_pg_tst:
  covid_out_tst:
  covid_in_tst:
  covid_clean_tst:

networks:
  web:
 
services:  

  api:
    build: api
    container_name: api
    networks:
      - web
    env_file:
      - api/api.env
    volumes:
      - covid_in:/tmp/input
    ports:
      - "8234:8888" # changed because 8888 conflicted on my server

  scraper:
    build: scraper
    container_name: scraper
    networks:
      - web
    env_file:
      - scraper/scrape.env
    environment:
      - PRODUCTION=False
    volumes:
      - ./scraper:/tmp/
      - covid_out_tst:/tmp/

  tidy:
    build: tidy
    container_name: tidy
    networks:
      - web
    env_file:
      - tidy/tidy.env
    volumes:
      - ./tidy:/tmp/
      - covid_out_tst:/tmp/output
      - covid_in_tst:/tmp/input
      - covid_clean_tst:/tmp/clean
    environment:
      - PRODUCTION=False
      
  db:
    build: ./covidb
    container_name: covidb
    environment:
      - PG_DATABASE=covidb
      - PG_PRIMARY_USER=cvadmin
      - PG_PRIMARY_PASSWORD=LovingLungfish
      - PG_MODE=primary
      - PG_USER=jesters
      - PG_PASSWORD=AngryMoose78
      - PG_ROOT_PASSWORD=AngryMoose77
      - PGDATA_PATH_OVERRIDE=persistent
      - PGHOST=/tmp
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=512MB
      - TIMEZONE=UTC
      - PG_PRIMARY_PORT=5432
      - BACKUP_PATH=latest
    networks:
      - web
    expose:       # expose the port to only be internal
      - 5432
    volumes:
      - covid_out_tst:/tmp/output
      - covidb_pg_tst:/data
      
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    networks:
      - web
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    expose:
      - 4444
