version: '3.1'

volumes:
  covid_pgvolume:
    external: true

networks:
  web:


services:

  db:
    image: crunchydata/crunchy-postgres-gis:centos7-12.2-4.1.2
    volumes:
      - covid_pgvolume:/pgdata
      - ./covidb/pgconf:/pgconf
    ports:
      - "5006:5432"
    networks:
      - web
    environment:
      - PG_DATABASE=covidb
      - PG_PRIMARY_USER=cvadmin
      - PG_PRIMARY_PASSWORD=LovingLungfish
      - PG_MODE=primary
      - PG_USER=jesters
      - PG_PASSWORD=AngryMoose78
      - PG_ROOT_PASSWORD=AngryMoose77
      - PGDATA_PATH_OVERRIDE=persistent
      - PGHOST=/tmp
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=512MB
      - TIMEZONE=UTC
      - PG_PRIMARY_PORT=5432
      - BACKUP_PATH=latest
    expose:
      - '5005'

  scraper:
    build: scraper
    volumes:
      - ./scraper/bin:/tmp/bin
      - ./scraper/cvpy:/tmp/cvpy
      - ./scraper/scripts:/tmp/scripts
    env_file:
      - scraper_db.env
    networks:
      - web
