version: '3.1'

volumes:
  covidb_pg:
    external: true
  covid_out:
    external: true
  covid_in:
    external: true
  covid_clean:
    external: true

networks:
  web:
 
services:  

  api:
    build: ./api
    container_name: api
    networks:
      - web
    env_file:
      - api/api.env
    volumes:
      - covid_in:/tmp/input
    ports:
      - "8888:8888"

  scraper:
    build: ./scraper
    container_name: scraper
    networks:
      - web
    env_file:
      - scraper/scrape.env
    volumes:
      - covid_out:/tmp/output
      - covid_in:/tmp/input

  tidy:
    build: ./tidy
    container_name: tidy
    networks:
      - web
    env_file:
      - tidy/tidy.env
    volumes:
      - covid_out:/tmp/output
      - covid_in:/tmp/input
      - covid_clean:/tmp/clean

  shiny:
    build: ./shiny
    container_name: shiny
    networks:
      - web
    env_file:
      - shiny/shiny.env
      
  db:
    build: ./covidb
    container_name: db
    environment:
      - PG_DATABASE=covidb
      - PG_PRIMARY_USER=cvadmin
      - PG_PRIMARY_PASSWORD=LovingLungfish
      - PG_MODE=primary
      - PG_USER=jesters
      - PG_PASSWORD=AngryMoose78
      - PG_ROOT_PASSWORD=AngryMoose77
      - PGDATA_PATH_OVERRIDE=persistent
      - PGHOST=/data
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=512MB
      - TIMEZONE=UTC
      - PG_PRIMARY_PORT=5432
      - BACKUP_PATH=latest
      - PGMODE=primary
    networks:
      - web
    ports:
      - "5432:5432"
    volumes:
      - covid_clean:/tmp/clean
      - covidb_pg:/data
      
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    networks:
      - web
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    ports:
      - "4444:4444"
