version: '3.1'

volumes:
  covidb_pg:
    external: true
  covid_out: 
    external: true


networks:
  web:
 

services:  

  api:
    build: api
    container_name: api
    networks:
      - web
    ports:
      - "8888:8888"

  scraper:
    build: scraper
    container_name: scraper
    networks:
      - web
    env_file:
      - db.env
      - scraper/scrape.env
    volumes:
      - covidb_pg:/pgdata

  hub:
    image: selenium/standalone-chrome:latest
    container_name: hub
    networks:
      - web
    ports:
      - "4444:4444"

  tidy:
    build: tidy
    container_name: tidy
    networks:
      - web
    env_file:
      - db.env
      - tidy/tidy.env
    ports:
      - "5432:5432"
    volumes:
      - covid_out:/tmp/output
      
  
      
  covidb:
    build: covidb
    container_name: covidb
    networks:
      - web
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - covid_out:/tmp/output
      
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    depends_on:
      - hub
    networks:
      - web
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
