version: '3.1'

volumes:
#  covidb_pg:
#    external: true
  covid_out:
#    external: true
  pgvolume:


networks:
  web:
 

services:  

  scraper:
    build: scraper
    container_name: scraper
    networks:
      - web
    env_file:
      - db.env
      - scraper/scrape.env
    volumes:
      - pgvolume:/pgdata
  #hub:
    #image: selenium/standalone-chrome:latest
    #container_name: hub
    #networks:
      #- web
    #ports:
      #- "4444:4444"

  tidy:
    build: tidy
    container_name: tidy
    networks:
      - web
    env_file:
      - db.env
      - tidy/tidy.env
    volumes:
      - covid_out:/tmp/output
      
  db:
    build: ./covidb
    environment:
      - PG_DATABASE=covidb
      - PG_PRIMARY_USER=cvadmin
      - PG_PRIMARY_PASSWORD=LovingLungfish
      - PG_MODE=primary
      - PG_USER=jesters
      - PG_PASSWORD=AngryMoose78
      - PG_ROOT_PASSWORD=AngryMoose77
      - PGDATA_PATH_OVERRIDE=persistent
      - PGHOST=/tmp
      - MAX_CONNECTIONS=100
      - SHARED_BUFFERS=512MB
      - TIMEZONE=UTC
      - PG_PRIMARY_PORT=5432
      - BACKUP_PATH=latest
#    container_name: covidb
    networks:
      - web
#    env_file:
#      - db.env
#    ports:
#      - "5432:5432"
    volumes:
      - covid_out:/tmp/output
#      - covidb_pg:/data
      
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
#    depends_on:
#      - hub
    networks:
      - web
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
#    expose:
#      - "4444:4444"
